# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jPVezOKXOM9IrDvaspOmbZaYgijSbCkQ
"""

import pandas

"""Задача 40: Работать с файлом california_housing_train.csv, который находится в папке
sample_data. Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)

Работать с файлом california_housing_train.csv, который находится в папке sample_data.
"""

df = pandas.read_csv('sample_data/california_housing_train.csv')
df

"""Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)

median_house_value Перевод как "средняя стоимость дома":
"""

df[(df['population']>0) & (df['population']<500)]['median_house_value']

"""Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population) (Если же задача стоит другая, определить среднюю цену в колонке средняя стоимость дома, то вот решение:)"""

df[(df['population']>0) & (df['population']<500)]['median_house_value'].mean()

"""Задача 42: Узнать какая максимальная households в зоне минимального значения population"""

df[df['population']==df['population'].min()]['households'].max()